
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 14 22:18:47 CST 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 29;
  public static final int PUNTO = 28;
  public static final int INSERTAR = 24;
  public static final int OR = 30;
  public static final int MENORIGUAL = 17;
  public static final int IGUAL = 9;
  public static final int numero = 4;
  public static final int ELIMINAR = 27;
  public static final int ERROR = 34;
  public static final int UBICACION = 10;
  public static final int MENORQ = 16;
  public static final int PROYECTO = 31;
  public static final int COMILLAS = 14;
  public static final int FILTRAR = 22;
  public static final int VALORES = 25;
  public static final int ASIGNAR = 23;
  public static final int ACTUALIZAR = 26;
  public static final int COMA = 5;
  public static final int MAYORQ = 15;
  public static final int NOMBRE = 6;
  public static final int EOF = 0;
  public static final int INICIOCAR = 2;
  public static final int MAYORIGUAL = 18;
  public static final int TEXTO = 32;
  public static final int error = 1;
  public static final int DIAGONAL = 13;
  public static final int CORCHETEABRE = 11;
  public static final int ARCHIVO = 20;
  public static final int EN = 21;
  public static final int INICIOPROY = 3;
  public static final int CARPETA = 7;
  public static final int FIN = 8;
  public static final int PATH = 33;
  public static final int CORCHETECIERRA = 12;
  public static final int SELECCIONAR = 19;
}

