/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1sql.UI;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import practica1sql.Backend.Archivo;
import practica1sql.Backend.CreadorArchivoIde;

/**
 *
 * @author astridmc
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuAbrir = new javax.swing.JMenuItem();
        MenuCrearNuevo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barraMenu.setBackground(new java.awt.Color(1, 1, 1));
        barraMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barraMenu.setPreferredSize(new java.awt.Dimension(347, 60));

        jMenu1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(195, 195, 195)));
        jMenu1.setForeground(new java.awt.Color(254, 254, 254));
        jMenu1.setText("Proyectos ");
        jMenu1.setFont(new java.awt.Font("Gargi", 0, 24)); // NOI18N

        MenuAbrir.setBackground(new java.awt.Color(1, 1, 1));
        MenuAbrir.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 24)); // NOI18N
        MenuAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1sql/UI/Imagenes/abrir.png"))); // NOI18N
        MenuAbrir.setText("Abrir Proyecto ");
        MenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(MenuAbrir);

        MenuCrearNuevo.setBackground(new java.awt.Color(1, 1, 1));
        MenuCrearNuevo.setFont(new java.awt.Font("Nimbus Roman No9 L", 0, 24)); // NOI18N
        MenuCrearNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1sql/UI/Imagenes/5e407e7e04542_1581285073_5e407e7e044e5.png"))); // NOI18N
        MenuCrearNuevo.setText("Crear Nuevo");
        MenuCrearNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCrearNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCrearNuevo);

        barraMenu.add(jMenu1);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1018, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAbrirActionPerformed

    }//GEN-LAST:event_MenuAbrirActionPerformed

    private void MenuCrearNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCrearNuevoActionPerformed
        JFileChooser seleccionar = new JFileChooser();
        seleccionar.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        seleccionar.setMultiSelectionEnabled(false);
        Archivo arch = new Archivo();
        String direccion = arch.obtenerRuta(seleccionar);
        if (direccion != null) {
            System.out.println(direccion);
            String nombreProyecto = JOptionPane.showInputDialog(
                    this,
                    "Input dialog",
                    JOptionPane.QUESTION_MESSAGE);  // el icono sera un iterrogante
            arch.setPath(direccion+"/"+nombreProyecto);
            System.out.println("El usuario ha escrito " + nombreProyecto);
            System.out.println(arch.getPath());
            System.out.println(arch.crearCarpeta());
            CreadorArchivoIde crearArch = new CreadorArchivoIde();
            crearArch.creador(direccion+"/"+nombreProyecto, nombreProyecto);
        }

    
    }//GEN-LAST:event_MenuCrearNuevoActionPerformed
private void Diseño() {
        this.setResizable(true);
        this.setTitle("Inicio");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAbrir;
    private javax.swing.JMenuItem MenuCrearNuevo;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
